### ISSUE TITLE
jquery.fancytree.js not found after composer update

### ISSUE THREAD

**Issue by inotloh** [yii2mod/yii2-tree#4]
![image](https://user-images.githubusercontent.com/14199662/32770853-7395fbf4-c93a-11e7-8dfd-a39fc7a0abea.png)
After update js file not found. In vendor in path bower/fancytree/dist/jquery.fancytree.js not exists, but in 
bower/fancytree/dist/module/jquery.fancytree.js exists, but in Asset class this path bower/fancytree/dist/jquery.fancytree.js

**Comment by ihorchepurnyi** [comment]
Hi, fixed. Please, update your package.

**Comment by ihorchepurnyi** [comment]
closed by 7c1d0603aed724045c7c897555087566a89e31c6

**Comment by ihorchepurnyi** [comment]
I'm sorry for late response.
